build:
	docker build -t registry.code.em32.net/overviewer/minecraft-overviewer:base . 

push:
	docker push registry.code.em32.net/overviewer/minecraft-overviewer:base

run:
	docker run --rm -it registry.code.em32.net/overviewer/minecraft-overviewer:base /bin/bash

