build:
	docker build -t code.em32.net:14567/overviewer/minecraft-overviewer:base . 

push:
	docker push code.em32.net:14567/overviewer/minecraft-overviewer:base

run:
	docker run --rm -it code.em32.net:14567/overviewer/minecraft-overviewer:base /bin/bash

